/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 13 20:58:46 GMT 2026
 */

package org.apache.syncope.core.persistence.jpa.dao;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.syncope.common.lib.types.AnyTypeKind;
import org.apache.syncope.core.persistence.jpa.dao.SearchSupport;
import org.apache.syncope.core.persistence.jpa.dao.SearchViewSupport;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SearchSupport_ESTest extends SearchSupport_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SearchSupport searchSupport0 = new SearchSupport((AnyTypeKind) null);
      // Undeclared exception!
      try { 
        searchSupport0.table();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.persistence.jpa.dao.SearchSupport", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SearchSupport searchSupport0 = new SearchSupport((AnyTypeKind) null);
      // Undeclared exception!
      try { 
        searchSupport0.role();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.persistence.jpa.dao.SearchSupport", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SearchViewSupport searchViewSupport0 = new SearchViewSupport((AnyTypeKind) null);
      // Undeclared exception!
      try { 
        searchViewSupport0.relationship();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.persistence.jpa.dao.SearchSupport", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SearchSupport searchSupport0 = new SearchSupport((AnyTypeKind) null);
      // Undeclared exception!
      try { 
        searchSupport0.membership();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.persistence.jpa.dao.SearchSupport", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SearchViewSupport searchViewSupport0 = new SearchViewSupport((AnyTypeKind) null);
      // Undeclared exception!
      try { 
        searchViewSupport0.groupResource();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.syncope.core.persistence.jpa.dao.SearchSupport", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.ANY_OBJECT;
      SearchSupport searchSupport0 = new SearchSupport(anyTypeKind0);
      SearchSupport.SearchView searchSupport_SearchView0 = searchSupport0.field();
      assertNotNull(searchSupport_SearchView0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.USER;
      SearchSupport searchSupport0 = new SearchSupport(anyTypeKind0);
      SearchSupport.SearchView searchSupport_SearchView0 = searchSupport0.field();
      assertNotNull(searchSupport_SearchView0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.GROUP;
      SearchSupport searchSupport0 = new SearchSupport(anyTypeKind0);
      SearchSupport.SearchView searchSupport_SearchView0 = searchSupport0.field();
      assertNotNull(searchSupport_SearchView0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SearchSupport.SearchView searchSupport_SearchView0 = new SearchSupport.SearchView("_entitlements", "_entitlements");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.ANY_OBJECT;
      SearchViewSupport searchViewSupport0 = new SearchViewSupport(anyTypeKind0);
      SearchViewSupport searchViewSupport1 = searchViewSupport0.asSearchViewSupport();
      assertSame(searchViewSupport0, searchViewSupport1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.USER;
      SearchSupport searchSupport0 = new SearchSupport(anyTypeKind0);
      // Undeclared exception!
      try { 
        searchSupport0.asSearchViewSupport();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Not an SearchViewSupport instance
         //
         verifyException("org.apache.syncope.core.persistence.jpa.dao.SearchSupport", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.USER;
      SearchSupport searchSupport0 = new SearchSupport(anyTypeKind0);
      SearchSupport.SearchView searchSupport_SearchView0 = searchSupport0.membership();
      assertNotNull(searchSupport_SearchView0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.GROUP;
      SearchViewSupport searchViewSupport0 = new SearchViewSupport(anyTypeKind0);
      SearchSupport.SearchView searchSupport_SearchView0 = searchViewSupport0.relationship();
      assertNotNull(searchSupport_SearchView0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.USER;
      SearchSupport searchSupport0 = new SearchSupport(anyTypeKind0);
      SearchSupport.SearchView searchSupport_SearchView0 = searchSupport0.relationship();
      assertNotNull(searchSupport_SearchView0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.USER;
      SearchSupport searchSupport0 = new SearchSupport(anyTypeKind0);
      SearchSupport.SearchView searchSupport_SearchView0 = searchSupport0.table();
      assertNotNull(searchSupport_SearchView0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.GROUP;
      SearchSupport searchSupport0 = new SearchSupport(anyTypeKind0);
      SearchSupport.SearchView searchSupport_SearchView0 = searchSupport0.table();
      assertNotNull(searchSupport_SearchView0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.ANY_OBJECT;
      SearchViewSupport searchViewSupport0 = new SearchViewSupport(anyTypeKind0);
      SearchSupport.SearchView searchSupport_SearchView0 = searchViewSupport0.table();
      assertNotNull(searchSupport_SearchView0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.ANY_OBJECT;
      SearchViewSupport searchViewSupport0 = new SearchViewSupport(anyTypeKind0);
      SearchSupport.SearchView searchSupport_SearchView0 = searchViewSupport0.role();
      assertNotNull(searchSupport_SearchView0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.USER;
      SearchSupport searchSupport0 = new SearchSupport(anyTypeKind0);
      SearchSupport.SearchView searchSupport_SearchView0 = searchSupport0.groupResource();
      assertNotNull(searchSupport_SearchView0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.USER;
      SearchSupport searchSupport0 = new SearchSupport(anyTypeKind0);
      SearchSupport.SearchView searchSupport_SearchView0 = searchSupport0.entitlements();
      assertNotNull(searchSupport_SearchView0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.GROUP;
      SearchSupport searchSupport0 = new SearchSupport(anyTypeKind0);
      SearchSupport.SearchView searchSupport_SearchView0 = searchSupport0.resource();
      assertNotNull(searchSupport_SearchView0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      AnyTypeKind anyTypeKind0 = AnyTypeKind.GROUP;
      SearchSupport searchSupport0 = new SearchSupport(anyTypeKind0);
      SearchSupport.SearchView searchSupport_SearchView0 = searchSupport0.auxClass();
      assertNotNull(searchSupport_SearchView0);
  }
}
